name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # These secrets should be set in the repository settings:
  #   GCP_PROJECT_ID
  #   GCP_SERVICE_ACCOUNT_KEY

  GKE_CLUSTER: 'unotes-000-gke'
  GKE_ZONE: 'us-east4-a'
  GKE_IMAGE: 'jurny-rider-backend'
  K8S_MANIFEST: './deployments/deployment.yaml'

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployments/terraform
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-service-account-key.json
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - run: echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > $GOOGLE_APPLICATION_CREDENTIALS

      - run: terraform init

      - run: terraform validate

      - run: terraform plan

      - name: apply infrastructure
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve

  build-deploy:
    needs: infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup gcloud
        uses: google-github-actions/auth@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: setup docker
        run: gcloud --quiet auth configure-docker

      - name: build docker image
        run: |
          docker build \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GKE_IMAGE }}:latest \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GKE_IMAGE }}:${{ github.sha }} \
            .

      - name: push docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GKE_IMAGE }}:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.GKE_IMAGE }}:${{ github.sha }}

      - name: setup kubectl
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
